version: '3.9'

services:
  old-db:
    container_name: old-messenger_db
    image: postgres:18.3-alpine3.23
    volumes:
      - old-messenger-db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./backend/old/.env
    networks:
      - messenger_network
  
  old-backend:
    container_name: old-messenger_backend
    build:
      context: ./backend/old
    depends_on:
      - old-db
    ports:
      - "8080:8080"
    env_file:
      - ./backend/old/.env
    networks:
      - messenger_network

volumes:
  old-messenger-db:

networks:
  messenger_network:
    driver: bridge