version: '3.9'

services:
  db:
    container_name: messenger_db
    image: postgres
    volumes:
      - messenger_db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    networks:
      - messenger_network
  
  backend:
    image: messenger_backend
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    networks:
      - messenger_network

volumes:
  messenger_db:

networks:
  messenger_network:
    driver: bridge