shutdown:
  shutdown_timeout: 5
vault:
  path: "secret/data/auth-service"
expired_token_clearing_worker:
  interval_ms: 1000
  batch_size: 1000
  count: 5
user_data_deletion_tasks_consumer:
  count: 5
  kafka_consumer:
    group_id: "auth-service-consumer"
    topic: "user-data-deletion-tasks"
    batch_size: 1000
    batch_timeout_ms: 1000
    name: "user_data_deletion_tasks_consumer"
