metrics_server:
  port: ":8080"
shutdown:
  shutdown_timeout: 15
vault:
  path: "secret/data/user-service"
user_data_deletion_tasks_producer:
  topic: "user-data-deletion-tasks"
  client_id: "user-service"
  write_timeout: 30
  name: "user_data_deletion_tasks_producer"
unconfirmed_users_data_clearing_worker:
  count: 5
  interval_ms: 1000
  no_data_interval_ms: 30000
  batch_size: 1000
deleted_users_data_clearing_worker:
  count: 5
  interval_ms: 1000
  no_data_interval_ms: 30000
  batch_size: 1000
unban_temporarily_banned_users_worker:
  count: 5
  interval_ms: 1000
  no_data_interval_ms: 30000
  batch_size: 1000
user_data_deletion_tasks_sending_worker:
  count: 5
  interval_ms: 1000
  retry_interval_ms: 300000
  batch_size: 1000
